//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrmTesterDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrmTesterDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose application mode.
        /// </summary>
        public static string AppMode {
            get {
                return ResourceManager.GetString("AppMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bulk.
        /// </summary>
        public static string Bulk {
            get {
                return ResourceManager.GetString("Bulk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create operation.
        /// </summary>
        public static string CreateOperation {
            get {
                return ResourceManager.GetString("CreateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete operation.
        /// </summary>
        public static string DeleteOperation {
            get {
                return ResourceManager.GetString("DeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Difference between averages.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entity Framework average time.
        /// </summary>
        public static string EfAverage {
            get {
                return ResourceManager.GetString("EfAverage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entity Framework coefficient of variation.
        /// </summary>
        public static string EfCoefficentOfVariation {
            get {
                return ResourceManager.GetString("EfCoefficentOfVariation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entity Framework standard deviation.
        /// </summary>
        public static string EfStandardDeviation {
            get {
                return ResourceManager.GetString("EfStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Execute test.
        /// </summary>
        public static string ExecuteTest {
            get {
                return ResourceManager.GetString("ExecuteTest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export tests excel file.
        /// </summary>
        public static string ExportToCSV {
            get {
                return ResourceManager.GetString("ExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export tests to file.
        /// </summary>
        public static string ExportToFile {
            get {
                return ResourceManager.GetString("ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generate diagram.
        /// </summary>
        public static string GenerateDiagram {
            get {
                return ResourceManager.GetString("GenerateDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Load file.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Many to many.
        /// </summary>
        public static string ManyToMany {
            get {
                return ResourceManager.GetString("ManyToMany", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu nHibernate average time.
        /// </summary>
        public static string NHibernateAverage {
            get {
                return ResourceManager.GetString("NHibernateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu nHibernate coefficient of variation.
        /// </summary>
        public static string NHibernateCoefficentOfVariation {
            get {
                return ResourceManager.GetString("NHibernateCoefficentOfVariation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu nHibernate standard deviation.
        /// </summary>
        public static string NHibernateStandardDeviation {
            get {
                return ResourceManager.GetString("NHibernateStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu One to many.
        /// </summary>
        public static string OneToMany {
            get {
                return ResourceManager.GetString("OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu One to one.
        /// </summary>
        public static string OneToOne {
            get {
                return ResourceManager.GetString("OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operation Type.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Relationship type.
        /// </summary>
        public static string RelationshipType {
            get {
                return ResourceManager.GetString("RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Repetitions.
        /// </summary>
        public static string Repetitions {
            get {
                return ResourceManager.GetString("Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start new test.
        /// </summary>
        public static string StartNewTest {
            get {
                return ResourceManager.GetString("StartNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Test name.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Update operation.
        /// </summary>
        public static string UpdateOperation {
            get {
                return ResourceManager.GetString("UpdateOperation", resourceCulture);
            }
        }
    }
}
