//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrmTesterDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrmTesterDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tests.
        /// </summary>
        public static string AllTests {
            get {
                return ResourceManager.GetString("AllTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose application mode.
        /// </summary>
        public static string AppMode {
            get {
                return ResourceManager.GetString("AppMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Chart.
        /// </summary>
        public static string AverageChart {
            get {
                return ResourceManager.GetString("AverageChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk.
        /// </summary>
        public static string Bulk {
            get {
                return ResourceManager.GetString("Bulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Coefficent of Variation Chart.
        /// </summary>
        public static string CoVChart {
            get {
                return ResourceManager.GetString("CoVChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Operation.
        /// </summary>
        public static string CreateOperation {
            get {
                return ResourceManager.GetString("CreateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during test. Please make sure that your configuration is proper..
        /// </summary>
        public static string DBException {
            get {
                return ResourceManager.GetString("DBException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Operation.
        /// </summary>
        public static string DeleteOperation {
            get {
                return ResourceManager.GetString("DeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference Between Averages.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework Average Time.
        /// </summary>
        public static string EfAverage {
            get {
                return ResourceManager.GetString("EfAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework Coefficient of Variation.
        /// </summary>
        public static string EfCoefficentOfVariation {
            get {
                return ResourceManager.GetString("EfCoefficentOfVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework Standard Deviation.
        /// </summary>
        public static string EfStandardDeviation {
            get {
                return ResourceManager.GetString("EfStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Test.
        /// </summary>
        public static string ExecuteTest {
            get {
                return ResourceManager.GetString("ExecuteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tests To Excel.
        /// </summary>
        public static string ExportToCSV {
            get {
                return ResourceManager.GetString("ExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results to Excel operation completed successfully..
        /// </summary>
        public static string ExportToExcelSuccess {
            get {
                return ResourceManager.GetString("ExportToExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Statistics.
        /// </summary>
        public static string ExportToFile {
            get {
                return ResourceManager.GetString("ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate diagram.
        /// </summary>
        public static string GenerateDiagram {
            get {
                return ResourceManager.GetString("GenerateDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GenerateLabel {
            get {
                return ResourceManager.GetString("GenerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD TEST STATISTICS.
        /// </summary>
        public static string LoadStats {
            get {
                return ResourceManager.GetString("LoadStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many to Many.
        /// </summary>
        public static string ManyToMany {
            get {
                return ResourceManager.GetString("ManyToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW TEST.
        /// </summary>
        public static string NewTest {
            get {
                return ResourceManager.GetString("NewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nHibernate Average Time.
        /// </summary>
        public static string NHibernateAverage {
            get {
                return ResourceManager.GetString("NHibernateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nHibernate Coefficient of Variation.
        /// </summary>
        public static string NHibernateCoefficentOfVariation {
            get {
                return ResourceManager.GetString("NHibernateCoefficentOfVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nHibernate Standard Deviation.
        /// </summary>
        public static string NHibernateStandardDeviation {
            get {
                return ResourceManager.GetString("NHibernateStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One to Many.
        /// </summary>
        public static string OneToMany {
            get {
                return ResourceManager.GetString("OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One to One.
        /// </summary>
        public static string OneToOne {
            get {
                return ResourceManager.GetString("OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Type.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string RelationshipType {
            get {
                return ResourceManager.GetString("RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions.
        /// </summary>
        public static string Repetitions {
            get {
                return ResourceManager.GetString("Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time [ms].
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Chart.
        /// </summary>
        public static string SaveChart {
            get {
                return ResourceManager.GetString("SaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chart operation completed successfully..
        /// </summary>
        public static string SaveChartSuccess {
            get {
                return ResourceManager.GetString("SaveChartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save statistics operation completed successfully..
        /// </summary>
        public static string SaveFileSuccess {
            get {
                return ResourceManager.GetString("SaveFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Standard Deviation Chart.
        /// </summary>
        public static string SDChart {
            get {
                return ResourceManager.GetString("SDChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Test.
        /// </summary>
        public static string StartNewTest {
            get {
                return ResourceManager.GetString("StartNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Operation.
        /// </summary>
        public static string UpdateOperation {
            get {
                return ResourceManager.GetString("UpdateOperation", resourceCulture);
            }
        }
    }
}
